import DashboardTemplate from "@/components/dashboard";
import MenuList from "../../menuList";
export const metadata = {
  title: "Landing Page | KurbanQ",
  description: "Generated by create next app",
};
type PropsLayout = {
  children: React.ReactNode;
};
const RootLayout = ({ children }: PropsLayout) => {
  return (
    <DashboardTemplate title="Landing Page" id="landing page" menuList={MenuList}>
      {children}
    </DashboardTemplate>
  );
};
export default RootLayout;
